### ISSUE TITLE
about principle and algorithm

### ISSUE THREAD

**Issue by stuxiaozhang** [ParthPathak27/Social-Distancing-Detector#2]
hi! this is so coooooool!and i have a question.What is the principle and algorithm？

**Comment by ParthPathak27** [comment]
It consists of three main steps: calibration, detection, and measurement
Ref: [](https://landing.ai/landing-ai-creates-an-ai-tool-to-help-customers-monitor-social-distancing-in-the-workplace/)

**Comment by parthsompura** [comment]
> hi! this is so coooooool!and i have a question.What is the principle and algorithm？
It consists of three main steps: calibration, detection, and measurement.
[Ref](https://landing.ai/landing-ai-creates-an-ai-tool-to-help-customers-monitor-social-distancing-in-the-workplace/)

**Comment by stuxiaozhang** [comment]
thanks for replying me.and i wanna ask how did you calculate real distance between people？how did you transform the camera photo into plane graph...hhh

**Comment by parthsompura** [comment]
As the input video may be taken from an arbitrary perspective view, the first step of the pipeline is computing the transform (more specifically, the homography) that morphs the perspective view into a bird’s-eye (top-down) view. We term this process **calibration**. As the input frames are monocular (taken from a single camera), the simplest calibration method involves selecting four points in the perspective view and mapping them to the corners of a rectangle in the bird’s-eye view. This assumes that every person is standing on the same flat ground plane. From this mapping, we can derive a transformation that can be applied to the entire perspective image. This method, while well-known, can be tricky to apply correctly. As such, we have built a lightweight tool that enables even non-technical users to calibrate the system in real-time.

During the calibration step, we also estimate the scale factor of the bird’s eye view, e.g. how many pixels correspond to 6 feet in real life.

Ref: [click here](https://landing.ai/landing-ai-creates-an-ai-tool-to-help-customers-monitor-social-distancing-in-the-workplace/) for more detail.

**Comment by RuikunLi** [comment]
Hi, I am wondering how did you compute the homograph, which part of the code did this?
